language: go

go:
  - 1.x

install:
  - go get golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run ./...
  - go test -v -covermode=atomic -coverprofile=coverage.out -race -count=1 .
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
